# -*- coding: utf-8 -*-
"""10 – N-Gram Model (Uni-, Bi-, Tri-gram) Generation from Corpus.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8xz05IUdxfCouU4OUQVlzMQNobV6XHA
"""

# N-Gram Model (Uni-gram, Bi-gram, Tri-gram) Generation from Corpus

from collections import Counter
import re

# Sample corpus
corpus = """
Natural language processing is a field of artificial intelligence.
Natural language processing helps computers understand human language.
Language models are used in natural language processing.
"""

# Convert corpus into lowercase words
words = re.findall(r'\b\w+\b', corpus.lower())

# Function to generate n-grams
def generate_ngrams(words, n):
    return [tuple(words[i:i+n]) for i in range(len(words) - n + 1)]

# Generate Uni-grams, Bi-grams and Tri-grams
unigrams = generate_ngrams(words, 1)
bigrams = generate_ngrams(words, 2)
trigrams = generate_ngrams(words, 3)

# Count frequencies
unigram_counts = Counter(unigrams)
bigram_counts = Counter(bigrams)
trigram_counts = Counter(trigrams)

# Display results
print("----- UNIGRAMS -----")
for gram, count in unigram_counts.items():
    print(gram, ":", count)

print("\n----- BIGRAMS -----")
for gram, count in bigram_counts.items():
    print(gram, ":", count)

print("\n----- TRIGRAMS -----")
for gram, count in trigram_counts.items():
    print(gram, ":", count)