# -*- coding: utf-8 -*-
"""11 – Cosine Similarity Computation between Text Documents

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBEW9JhlbGOzQV3rGyFS-SIb7mTnwwIA
"""

# Cosine Similarity between Text Documents

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Sample documents
documents = [
    "Natural language processing is a field of artificial intelligence.",
    "Natural language processing helps computers understand human language.",
    "Machine learning is used in artificial intelligence."
]

# Convert documents into TF-IDF vectors
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

# Calculate cosine similarity
similarity_matrix = cosine_similarity(tfidf_matrix)

# Display similarity matrix
print("Cosine Similarity Matrix:")
print(similarity_matrix)

# Compare two documents
print("\nSimilarity between Document 1 and Document 2:",
      similarity_matrix[0][1])

print("Similarity between Document 1 and Document 3:",
      similarity_matrix[0][2])