# -*- coding: utf-8 -*-
"""12 – Word2Vec Word Embeddings using Gensim on a Custom Corpus

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXdwQy7kdCvdQQ9oql0GrE5QUrAc6xZ0
"""

import sys
!{sys.executable} -m pip install gensim

# Question 12:
# Word2Vec Word Embeddings using Gensim on a Custom Corpus

from gensim.models import Word2Vec

# --------------------------------------------------
# Step 1: Create a custom corpus
# --------------------------------------------------

sentences = [
    ["natural", "language", "processing", "is", "interesting"],
    ["natural", "language", "processing", "uses", "machine", "learning"],
    ["machine", "learning", "helps", "computers", "understand", "language"],
    ["word", "embeddings", "represent", "words", "as", "vectors"],
    ["word2vec", "creates", "word", "embeddings", "from", "text"],
    ["machine", "learning", "and", "natural", "language", "processing"],
    ["language", "models", "are", "used", "in", "NLP"],
    ["NLP", "helps", "computers", "process", "human", "language"]
]

# --------------------------------------------------
# Step 2: Train the Word2Vec model
# --------------------------------------------------

model = Word2Vec(
    sentences=sentences,
    vector_size=100,
    window=3,
    min_count=1,
    workers=4,
    sg=1,
    epochs=100
)

# --------------------------------------------------
# Step 3: Display vocabulary
# --------------------------------------------------

print("Vocabulary:")
print(list(model.wv.index_to_key))

# --------------------------------------------------
# Step 4: Display vector representation of a word
# --------------------------------------------------

word = "language"

print("\nVector representation of:", word)
print(model.wv[word])

# --------------------------------------------------
# Step 5: Find similar words
# --------------------------------------------------

print("\nWords similar to 'language':")

similar_words = model.wv.most_similar("language", topn=5)

for w, score in similar_words:
    print(w, ":", score)

# --------------------------------------------------
# Step 6: Calculate similarity between two words
# --------------------------------------------------

word1 = "language"
word2 = "processing"

similarity = model.wv.similarity(word1, word2)

print("\nSimilarity between", word1, "and", word2, ":")
print(similarity)

# --------------------------------------------------
# Step 7: Check whether a word exists
# --------------------------------------------------

if "machine" in model.wv:
    print("\n'machine' exists in the vocabulary.")
else:
    print("\n'machine' does not exist in the vocabulary.")