# -*- coding: utf-8 -*-
"""14: Text Similarity using Word Mover's Distance (WMD)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXdwQy7kdCvdQQ9oql0GrE5QUrAc6xZ0
"""

!pip install -q gensim POT

from gensim.models import Word2Vec

sentences = [
    ["i", "love", "machine", "learning"],
    ["machine", "learning", "is", "interesting"],
    ["i", "enjoy", "artificial", "intelligence"],
    ["artificial", "intelligence", "is", "interesting"],
    ["i", "love", "playing", "cricket"],
    ["cricket", "is", "my", "favorite", "sport"]
]

model = Word2Vec(
    sentences,
    vector_size=100,
    window=5,
    min_count=1,
    workers=1,
    seed=42
)

text1 = ["i", "love", "machine", "learning"]
text2 = ["machine", "learning", "is", "interesting"]
text3 = ["i", "enjoy", "artificial", "intelligence"]
text4 = ["cricket", "is", "my", "favorite", "sport"]

distance1 = model.wv.wmdistance(text1, text2)
distance2 = model.wv.wmdistance(text1, text3)
distance3 = model.wv.wmdistance(text1, text4)

print("Text 1:", " ".join(text1))
print("Text 2:", " ".join(text2))
print("Text 3:", " ".join(text3))
print("Text 4:", " ".join(text4))

print("\nWord Mover's Distance:")
print("Text 1 and Text 2:", distance1)
print("Text 1 and Text 3:", distance2)
print("Text 1 and Text 4:", distance3)

distances = {
    "Text 1 and Text 2": distance1,
    "Text 1 and Text 3": distance2,
    "Text 1 and Text 4": distance3
}

most_similar = min(distances, key=distances.get)

print("\nMost similar pair:")
print(most_similar)
print("Smallest WMD:", distances[most_similar])