# -*- coding: utf-8 -*-
"""15: Text Classification using Naive Bayes/SVM with TF-IDF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXdwQy7kdCvdQQ9oql0GrE5QUrAc6xZ0
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

texts = [
    "I love this movie",
    "This movie is excellent",
    "Amazing and wonderful movie",
    "I enjoyed this film",
    "This movie is very good",
    "I hate this movie",
    "This movie is terrible",
    "Very bad and boring movie",
    "I disliked this film",
    "This movie is disappointing"
]

labels = [
    "Positive",
    "Positive",
    "Positive",
    "Positive",
    "Positive",
    "Negative",
    "Negative",
    "Negative",
    "Negative",
    "Negative"
]

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(texts)

X_train, X_test, y_train, y_test = train_test_split(
    X, labels, test_size=0.3, random_state=42
)

model = MultinomialNB()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

new_text = [
    "This movie is amazing",
    "This movie is very bad"
]

new_vector = vectorizer.transform(new_text)

prediction = model.predict(new_vector)

for text, result in zip(new_text, prediction):
    print("\nText:", text)
    print("Category:", result)