# -*- coding: utf-8 -*-
"""15: Text Classification using Word Embeddings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXdwQy7kdCvdQQ9oql0GrE5QUrAc6xZ0
"""

from gensim.models import Word2Vec
import numpy as np
from sklearn.linear_model import LogisticRegression

sentences = [
    ["i", "love", "this", "movie"],
    ["this", "movie", "is", "excellent"],
    ["amazing", "and", "wonderful", "movie"],
    ["i", "hate", "this", "movie"],
    ["this", "movie", "is", "terrible"],
    ["bad", "and", "boring", "movie"]
]

labels = [1, 1, 1, 0, 0, 0]

model = Word2Vec(
    sentences,
    vector_size=50,
    window=3,
    min_count=1,
    workers=1,
    seed=42
)

def get_vector(sentence):
    vectors = []

    for word in sentence:
        if word in model.wv:
            vectors.append(model.wv[word])

    return np.mean(vectors, axis=0)

X = np.array([get_vector(sentence) for sentence in sentences])

classifier = LogisticRegression()
classifier.fit(X, labels)

test_sentences = [
    ["this", "movie", "is", "amazing"],
    ["this", "movie", "is", "bad"]
]

for sentence in test_sentences:
    vector = get_vector(sentence).reshape(1, -1)
    prediction = classifier.predict(vector)[0]

    if prediction == 1:
        print("Text:", " ".join(sentence))
        print("Category: Positive")
    else:
        print("Text:", " ".join(sentence))
        print("Category: Negative")