# -*- coding: utf-8 -*-
"""16: Sentiment Analysis using TextBlob and VADER

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXdwQy7kdCvdQQ9oql0GrE5QUrAc6xZ0
"""

!pip install -q vaderSentiment

from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

texts = [
    "I love this product. It is amazing!",
    "This movie is excellent and wonderful.",
    "I hate this product. It is terrible.",
    "The service is very bad and disappointing.",
    "The product is okay."
]

analyzer = SentimentIntensityAnalyzer()

for text in texts:

    blob = TextBlob(text)
    polarity = blob.sentiment.polarity

    if polarity > 0:
        textblob_sentiment = "Positive"
    elif polarity < 0:
        textblob_sentiment = "Negative"
    else:
        textblob_sentiment = "Neutral"

    score = analyzer.polarity_scores(text)
    compound = score["compound"]

    if compound >= 0.05:
        vader_sentiment = "Positive"
    elif compound <= -0.05:
        vader_sentiment = "Negative"
    else:
        vader_sentiment = "Neutral"

    print("Text:", text)
    print("TextBlob Polarity:", polarity)
    print("TextBlob Sentiment:", textblob_sentiment)
    print("VADER Scores:", score)
    print("VADER Sentiment:", vader_sentiment)
    print("-" * 50)