# -*- coding: utf-8 -*-
"""17: Topic Modeling using Latent Dirichlet Allocation (LDA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXdwQy7kdCvdQQ9oql0GrE5QUrAc6xZ0
"""

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

documents = [
    "machine learning algorithms are used in artificial intelligence",
    "deep learning and neural networks are important for AI",
    "artificial intelligence uses machine learning and deep learning",
    "football is a popular sport played by many people",
    "cricket and football are popular sports around the world",
    "sports players practice regularly to improve their performance"
]

vectorizer = CountVectorizer(stop_words="english")

X = vectorizer.fit_transform(documents)

lda = LatentDirichletAllocation(
    n_components=2,
    random_state=42
)

lda.fit(X)

words = vectorizer.get_feature_names_out()

for topic_number, topic in enumerate(lda.components_):
    print("\nTopic", topic_number + 1)

    top_words = topic.argsort()[-5:][::-1]

    for index in top_words:
        print(words[index], end=" ")

print()

document_topics = lda.transform(X)

print("\nDocument Topic Distribution:")

for i, distribution in enumerate(document_topics):
    print("Document", i + 1, ":", distribution)