# -*- coding: utf-8 -*-
"""18: Topic Modeling using Latent Semantic Analysis (LSA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXdwQy7kdCvdQQ9oql0GrE5QUrAc6xZ0
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

documents = [
    "machine learning is a part of artificial intelligence",
    "deep learning uses neural networks for artificial intelligence",
    "machine learning and deep learning are important AI technologies",
    "football is a popular sport around the world",
    "cricket and football are popular sports",
    "sports players practice regularly to improve performance"
]

vectorizer = TfidfVectorizer(stop_words="english")

X = vectorizer.fit_transform(documents)

lsa = TruncatedSVD(n_components=2, random_state=42)

lsa_matrix = lsa.fit_transform(X)

words = vectorizer.get_feature_names_out()

for topic_number, component in enumerate(lsa.components_):
    print("\nTopic", topic_number + 1)

    top_words = component.argsort()[-5:][::-1]

    for index in top_words:
        print(words[index], end=" ")

print("\n")

print("Document Topic Representation:")

for i, document in enumerate(lsa_matrix):
    print("Document", i + 1, ":", document)