# -*- coding: utf-8 -*-
"""20: Information Extraction (IE) from Structured/Unstructured Documents

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXdwQy7kdCvdQQ9oql0GrE5QUrAc6xZ0
"""

import spacy

nlp = spacy.load("en_core_web_sm")

text = """
Rahul Sharma joined Microsoft in Hyderabad on 15 August 2026.
He is working as a Software Engineer in the Artificial Intelligence department.
"""

doc = nlp(text)

print("Information Extracted:\n")

for ent in doc.ents:
    print("Entity:", ent.text)
    print("Type:", ent.label_)
    print()