# -*- coding: utf-8 -*-
"""21: Information Retrieval System with Ranking using TF-IDF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXdwQy7kdCvdQQ9oql0GrE5QUrAc6xZ0
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

documents = [
    "Machine learning is a branch of artificial intelligence",
    "Deep learning uses neural networks and machine learning",
    "Artificial intelligence is used in many applications",
    "Natural language processing deals with text and language",
    "Information retrieval helps users find relevant documents"
]

query = input("Enter your search query: ")

vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(documents)

query_vector = vectorizer.transform([query])

similarity = cosine_similarity(query_vector, tfidf_matrix)[0]

ranking = similarity.argsort()[::-1]

print("\nSearch Results:")
print("----------------")

for rank, index in enumerate(ranking, start=1):
    print("Rank:", rank)
    print("Similarity Score:", round(similarity[index], 4))
    print("Document:", documents[index])
    print()