# -*- coding: utf-8 -*-
"""9-TF-IDF Implementation and Comparison with BoW

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WA5_9A85xpQvtidJgoxBOJvbCN1-YBac
"""

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Sample corpus
documents = [
    "I love machine learning",
    "Machine learning is interesting",
    "I love natural language processing",
    "Machine learning is useful"
]

# -------------------------------
# Bag-of-Words (BoW)
# -------------------------------

bow_vectorizer = CountVectorizer()

bow_matrix = bow_vectorizer.fit_transform(documents)

print("========== BAG-OF-WORDS ==========")

print("\nFeature Names:")
print(bow_vectorizer.get_feature_names_out())

print("\nBoW Matrix:")
print(bow_matrix.toarray())


# -------------------------------
# TF-IDF
# -------------------------------

tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

print("\n========== TF-IDF ==========")

print("\nFeature Names:")
print(tfidf_vectorizer.get_feature_names_out())

print("\nTF-IDF Matrix:")
print(tfidf_matrix.toarray())


# -------------------------------
# Display document-wise comparison
# -------------------------------

print("\n========== COMPARISON ==========")

for i, document in enumerate(documents):

    print("\nDocument", i + 1, ":", document)

    print("BoW Vector:")
    print(bow_matrix.toarray()[i])

    print("TF-IDF Vector:")
    print(tfidf_matrix.toarray()[i])