# -*- coding: utf-8 -*-
"""Bag-of-Words (BoW) Vectorization and Representation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gw9wshXJ468i2ICPFoHNbsPBofMFn2iu
"""

from sklearn.feature_extraction.text import CountVectorizer

# Sample corpus
documents = [
    "I love machine learning",
    "Machine learning is interesting",
    "I love natural language processing",
    "Machine learning is useful"
]

# Create CountVectorizer object
vectorizer = CountVectorizer()

# Convert text into Bag-of-Words representation
X = vectorizer.fit_transform(documents)

# Display vocabulary
print("Vocabulary:")
print(vectorizer.vocabulary_)

# Display feature names
print("\nFeature Names:")
print(vectorizer.get_feature_names_out())

# Display BoW matrix
print("\nBag-of-Words Matrix:")
print(X.toarray())

# Display each document and its vector
print("\nDocument Vectors:")

for i, document in enumerate(documents):
    print("Document", i + 1, ":", document)
    print("Vector:", X.toarray()[i])